### PR TITLE
Use empty mesh in case of invalid filenames in Mesh declarations

### LINKED ISSUE #2069: Incorrect texturing for add-ons
**Describe the bug**
Reported by mobile user, reproducible on desktop. See screenshots

**To Reproduce**
1. Download [Earth's Auroras](https://celestia.mobi/resources/item?item=F8120336-675B-A499-4DE2-84C8529957CC) add-on
2. Go to Earth
3. See error

**Expected behavior**

Screenshot 2024-01-14 at 23 43 50

**Screenshots**

Screenshot 2024-01-14 at 23 42 33

**Additional context**

The bad commit is https://github.com/CelestiaProject/Celestia/commit/3d5ce7b885aa1693727a8d3177ddd6825ff4aa5e#diff-7139070d8ab8a118bba0171ff5da4b90b7fa199c9d6d94e99c72d426ae9848a1

@ajtribick

### PR DESCRIPTION
**Pull request by ajtribick**
- Special case `Mesh ""` to not log errors (used in some add-ons to avoid rendering geometry while still retaining the ability to have cloud maps, etc.)

Resolves #2069

### CODE REVIEW

File: src/celengine/meshmanager.h [hunk 1]
```diff
@@ -99,4 +99,6 @@ inline bool operator<(const GeometryInfo::ResourceKey& k0,
 
 using GeometryManager = ResourceManager<GeometryInfo>;
 
-extern GeometryManager* GetGeometryManager();
+inline GeometryManager geometryManager("models");
```
Comment (375gnu) [inline src/celengine/meshmanager.h:102]: only trivially constructable objects can be static. please return the old code.

**Review by 375gnu — CHANGES_REQUESTED** [review]

File: src/celengine/meshmanager.h (hunk 1 above)
Comment (ajtribick) [reply src/celengine/meshmanager.h:102]: returned.

**Comment by 375gnu** [comment]
I'm sorry but why did you closed the PR?

**Comment by ajtribick** [comment]
late night branch wrangling

**Review by 375gnu — APPROVED** [review]
