### PR TITLE
[qt] Fix startup crash with --url parameter

### LINKED ISSUE #2072: Strating celestia-qt with URL crashes the program
```
0x00007ffff700dd81 in CelestiaCore::setStartURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /redacted//libcelestia.so.1.7
(gdb) bt
#0  0x00007ffff700dd81 in CelestiaCore::setStartURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /redacted/libcelestia.so.1.7
#1  0x000055555558b95d in CelestiaAppWindow::init(CelestiaCommandLineOptions const&) ()
#2  0x000055555557ec62 in main ()

```

### PR DESCRIPTION
**Pull request by ajtribick**
- Reorganize startup to avoid clobbering FOV when using startup URL
- Make several appwin/glwidget methods private, mark overrides

Fixes #2072

### CODE REVIEW

File: src/celestia/qt/qtappwin.cpp [hunk 1]
```diff
@@ -479,6 +469,11 @@ CelestiaAppWindow::init(const CelestiaCommandLineOptions& options)
     timer->start();
 }
 
+void
+CelestiaAppWindow::startAppCore()
```
Comment (375gnu) [inline src/celestia/qt/qtappwin.cpp:473]: just `start`?

Comment (ajtribick) [reply src/celestia/qt/qtappwin.cpp:473]: Since there's already a constructor and an `init` method in terms of things that begin the object, I prefer to be slightly more explicit about precisely what this thing is starting.

**Review by 375gnu — APPROVED** [review]
