### PR TITLE
Fix unrecognition names directly searched or loaded.

### LINKED ISSUE #248: Greek letters parsing regression
As Celestia store names in already parsed form, it doesn't recognize directly entered or loaded greek names. Suggestion: parse provided names when searching for objects.

### PR DESCRIPTION
**Pull request by pirogronian**
Fixes #248 . Feel free to merge if once approved.

### CODE REVIEW

File: src/celutil/utf8.cpp [hunk 1]
```diff
@@ -772,39 +772,45 @@ std::string ReplaceGreekLetterAbbr(const std::string& str)
     Greek *instance = Greek::getInstance();
     std::string ret = str;
 
-    if (str[0] >= 'A' && str[0] <= 'Z' &&
-        str[1] >= 'A' && str[1] <= 'Z')
+    if (str[0] >= 'A' && str[0] <= 'Z')
```
Comment (375gnu) [inline src/celutil/utf8.cpp]: Could you explain what's wrong with this file?

Comment (pirogronian) [reply src/celutil/utf8.cpp]: I added replacement also for Greek letters names, not only for cannonical abbreviations.

Comment (375gnu) [reply src/celutil/utf8.cpp]: Ok. Could you move this change into its own commit with the small explanation as above?
