### PR TITLE
Don't read DDS header twice, reallow triggering eof()

### LINKED ISSUE #1167: DDS textures are broken since da5f621
Commit  da5f621 introduced common routines to read binary data. But it broke DDS textures:

image

This supposed to be Earth. The texture used is from the latest Celestia Origin.

### PR DESCRIPTION
**Pull request by ajtribick**
Fixes #1167

I'm not particularly happy about allowing the `eof()` condition at the end as this implies we are attempting to read more data than the file contains, but it seems to be necessary at least with the Celestia Origin .dds files. I will take another look at this in future, but in the meantime it addresses the issue for people using master builds.

### CODE REVIEW

File: src/celimage/dds.cpp [hunk 1]
```diff
@@ -144,7 +144,6 @@ Image* LoadDDSImage(const fs::path& filename)
     }
 
     char header[4];
-    in.read(header, sizeof header);
```
Comment (375gnu) [inline src/celimage/dds.cpp:147]: we should be more careful when reviewing changes

**Review by 375gnu — APPROVED** [review]

File: src/celimage/dds.cpp (hunk 1 above)
Comment (ajtribick) [reply src/celimage/dds.cpp:147]: Agreed. Apologies for the breakages along the way, but I do think it's important for an application that's dealing with user content to be a lot stricter about error checking the input files these days.
