### PR TITLE
Do not reserve for empty string

### LINKED ISSUE #1647: Spoiled text information
**Describe the bug**
https://github.com/CelestiaProject/Celestia/commit/67cbcc3a5cfbb63d572d5254540f3040b82014af spoils the text information displayed in the screen corners with some symbols.

**Screenshots**
image
image

**Desktop:**
 - OS: Linux.
 - Frontend: Qt.
 - Version: 1.7.0.

### PR DESCRIPTION
**Pull request by levinli303**
closes #1647

### CODE REVIEW

File: src/celutil/unicode.cpp [hunk 1]
```diff
@@ -60,8 +60,7 @@ bool UnicodeStringToWString(const icu::UnicodeString &input, std::wstring &outpu
 {
     if (input.length() == 0)
     {
-        output.resize(1);
-        output[0] = L'\0';
+        output.resize(0);
```
Comment (ajtribick) [inline src/celutil/unicode.cpp:63]: `output.clear()`

**Review by ajtribick — APPROVED** [review]
